name: nodule_py310

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10.20
  - pip
  - setuptools=80.9.0
  - numpy=2.2.6

  - pandas
  - scipy
  - scikit-learn
  - scikit-image
  - sqlalchemy
  - pydicom
  - simpleitk
  - imageio
  - pillow
  - matplotlib
  - seaborn
  - openpyxl
  - pyyaml
  - requests
  - tqdm
  - tabulate
  - ipython
  - ipykernel
  - nbconvert

  - pip:
      - pylidc